### PR TITLE
List

### PR DESCRIPTION
**Pull request by uncomputable**
Add list type + expression + example.

### CODE REVIEW

**Comment by uncomputable** [comment]
Depends on #13

**Comment by uncomputable** [comment]
Rebased

**Comment by apoelstra** [comment]
utACK aaadbd84f910dd73364ed5be18bbd788a4666297 except can you run the formatter on it?

A quick nice way to make sure every individual commit is formatted is to run `git rebase -x 'cargo +nightly fmt --check' master`. Or you can just add a commit at the end which formats everything.

**Comment by apoelstra** [comment]
Also, can you help me understand the difference between lists and arrays?

**Review by apoelstra — APPROVED** [review]
ACK 0fd58d180cc7d896443e31a60993721c3b515804

**Comment by uncomputable** [comment]
Arrays are fixed size, while lists have a variable size up to a maximum. Lists internally use arrays for efficient sharing.

This will become clear once I update the docs in a follow-up PR.

**Pull request merged**
